name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # Clean installation
      - name: Clean and Install
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      # Continue with your other steps like building and testing
      - name: Build
        run: npm run build

      # Optionally publish or other steps...
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
